version: '3'

services:
  web:
    build: .
    image: timvanmourik/braindr
    volumes:
      - .:/code
    command: bash bin/docker-command.bash
    ports:
      - "8080:8080"   # application server
